# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for cargo
  - package-ecosystem: "cargo"
    # Look for `Cargo.toml` and `Cargo.lock` files in the `root` directory
    directory: "/"
    # Check the Cargo for updates weekly
    schedule:
      interval: "weekly"
